### ISSUE TITLE
unorderable types: NoneType() >= int()

### ISSUE THREAD

**Issue by aman541992** [ArthurPBressan/py-fixedwidthwriter#5]
Hi,

I am getting a TypeError: unorderable types: NoneType() >= int() while running the same code that you have given for reference. could you please help?

**Comment by ArthurPBressan** [comment]
I took a crack at it, and I found out that the error happens when you use Python 3 to execute the code. 

This is a pretty old lib that I actually didn't use much, so it really didn't receive as much love as it deserved. Namely the lack of testing will make this fix a bit slower than I would have liked.

Can you use Python 2.7 meanwhile?

**Comment by CatarinaPBressan** [comment]
Should be on PyPi already
